### ISSUE TITLE
Crash when opening UI (divide by zero on getScaledProgress)

### ISSUE THREAD

**Issue by Kasama** [TheLMiffy1111/PackagedExCrafting#12]
Hello! First of all, thanks for the work on this mod, it definitely makes life easier when integrating AE and ExCrafting :smile: 

While playing [Not too Complicated](https://github.com/MechOrigin/NTC2), which has this mod on it, I crashed while looking at an `Ender Package Crafter` while it was crafting some items.

The crash states that

```
java.lang.ArithmeticException: / by zero
	at thelm.packagedexcrafting.tile.EnderCrafterTile.getScaledProgress(EnderCrafterTile.java:256) ~[packagedexcrafting:2.0.0.3] {re:classloading}
	at thelm.packagedexcrafting.client.screen.EnderCrafterScreen.func_230450_a_(EnderCrafterScreen.java:28) ~[packagedexcrafting:2.0.0.3] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?]
...
```
(full crash log [here](https://pastebin.com/WhLY7A1V))

The crash points me to [`getScaledProgress`](https://github.com/TheLMiffy1111/PackagedExCrafting/blob/1.18.2/src/main/java/thelm/packagedexcrafting/block/entity/EnderCrafterBlockEntity.java#L256) which has a division. Probably an easy fix would be to add an `if` there to make sure that `actualProgressReq` isn't `0`.

That might also be necessary on the other 6 implementations of `getScaledProgress` for the other machines.

**Comment by TheLMiffy1111** [comment]
Should be fixed
