### ISSUE TITLE
Crash - AppEng 15.1.0 has renamed RF to FE - Breaks API calls

### ISSUE THREAD

**Issue by TigerWalts** [TheLMiffy1111/PackagedExCrafting#15]
https://www.github.com/AppliedEnergistics/Applied-Energistics-2/pull/7737

```
java.lang.NoSuchFieldError: RF
	at thelm.packagedexcrafting.integration.appeng.blockentity.AEAdvancedCrafterBlockEntity.chargeMEEnergy(AEAdvancedCrafterBlockEntity.java:137) ~[PackagedExCrafting-1.20.1-3.4.0.8.jar%23470!/:3.4.0.8] {re:classloading}
	at thelm.packagedexcrafting.integration.appeng.blockentity.AEAdvancedCrafterBlockEntity.tick(AEAdvancedCrafterBlockEntity.java:49) ~[PackagedExCrafting-1.20.1-3.4.0.8.jar%23470!/:3.4.0.8] {re:classloading}
	at thelm.packagedauto.block.entity.BaseBlockEntity.tick(BaseBlockEntity.java:162) ~[PackagedAuto-1.20.1-3.4.4.16.jar%23469!/:3.4.4.16] {re:classloading}
```

**Comment by TheLMiffy1111** [comment]
Should be fixed by AE2 15.1.1
